### ISSUE TITLE
Soma blinds - could not read the gatt files

### ISSUE THREAD

**Issue by CrispinP** [sputnikdev/bluetooth-gatt-parser#8]
Hi,

edit: I removed the weird copy/paste stuff above :)

Could someone help with the gatt files? The binding is picking up the Soma Blinds but does not seem to be using the gatt files and showing the rest of the characteristics

I’ve got it in a folder which has access by openhab user. Folder is alongside the items and things folders.

org.bluetooth.characteristic.blind_position.xml

```
<?xml version="1.0" encoding="utf-8"?><!--Copyright 2011 Bluetooth SIG, Inc. All rights reserved.-->
<Characteristic xsi:noNamespaceSchemaLocation="http://schemas.bluetooth.org/Documents/characteristic.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Blind Position"
                type="org.bluetooth.characteristic.blind_position" uuid="1525" last-modified="2011-12-05"
                approved="No">
    <InformativeText>
        <Abstract>
			Position of blinds
        </Abstract>
    </InformativeText>
    <Value>
        <Field name="Position">
            <Requirement>Mandatory</Requirement>
            <Format>uint8</Format>
            <Unit>org.bluetooth.unit.percentage</Unit>
            <Minimum>0</Minimum>
            <Maximum>100</Maximum>
            <Enumerations>
                <Reserved start="101" end="255"/>
            </Enumerations>
        </Field>
    </Value>
</Characteristic>

```
org.bluetooth.service.blind_position.xml

```
<Service xsi:noNamespaceSchemaLocation="http://schemas.bluetooth.org/Documents/service.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Soma Blinds"
         type="org.bluetooth.service.blind_position" uuid="1861" last-modified="2018-09-06">
<InformativeText>
    <Abstract>
        Soma Blinds control
    </Abstract>
    <Summary>
        Controller for Soma Blinds
    </Summary>
</InformativeText>
<Dependencies>
    <Dependency>This service has no dependencies on other GATT-based services.</Dependency>
</Dependencies>
<GATTRequirements>
    <Requirement subProcedure="Write Characteristic Value">Mandatory</Requirement>
    <Requirement subProcedure="Notification">Mandatory</Requirement>
    <Requirement subProcedure="Read Characteristic Descriptors">Mandatory</Requirement>
    <Requirement subProcedure="Write Characteristic Descriptors">Mandatory</Requirement>
</GATTRequirements>
<Transports>
    <Classic>false</Classic>
    <LowEnergy>true</LowEnergy>
</Transports>
<ErrorCodes>
</ErrorCodes>
<Characteristics>
    <Characteristic name="Blind Position"
                    type="org.bluetooth.characteristic.blind_position">
        <InformativeText>Blind control
        </InformativeText>
        <Requirement>Mandatory</Requirement>
        <Properties>
            <Read>Excluded</Read>
            <Write>Excluded</Write>
            <WriteWithoutResponse>Excluded</WriteWithoutResponse>
            <SignedWrite>Excluded</SignedWrite>
            <ReliableWrite>Excluded</ReliableWrite>
            <Notify>Excluded</Notify>
            <Indicate>Mandatory</Indicate>
            <WritableAuxiliaries>Excluded</WritableAuxiliaries>
            <Broadcast>Excluded</Broadcast>
        </Properties>
    </Characteristic>
</Characteristics>
</Service>

```
The blinds have 4 characteristics - I’ve just tried to get the one working thus far.
from a python file I currently use control.py -

# battery
BATTERY_SERVICE_UUID 					= "0000180f-0000-1000-8000-00805f9b34fb".lower()
BATTERY_CHARACTERISTIC_UUID 			= "00002a19-0000-1000-8000-00805f9b34fb".lower()

# motor control
MOTOR_SERVICE_UUID 						= "00001861-B87F-490C-92CB-11BA5EA5167C".lower()
MOTOR_STATE_CHARACTERISTIC_UUID 		= "00001525-B87F-490C-92CB-11BA5EA5167C".lower()
MOTOR_CONTROL_CHARACTERISTIC_UUID 		= "00001530-B87F-490C-92CB-11BA5EA5167C".lower()
MOTOR_TARGET_CHARACTERISTIC_UUID 		= "00001526-B87F-490C-92CB-11BA5EA5167C".lower()
MOTOR_MOVE_UP = 69
MOTOR_MOVE_DOWN = 96

Original py file is here https://github.com/paolotremadio/SOMA-Smart-Shades-HTTP-API

Thanks

**Comment by vkolotov** [comment]
Hi @CrispinP,  sorry for a late reply.

Could you please enable DEBUG level for the gatt parser as per this?

```
log:set DEBUG org.sputnikdev.bluetooth.gattparser.spec
```

Then you should expect in the logs something like that:

```
13:28:57.924 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading services and characteristics from folder: /home/pi/.bluetooth_smart
13:28:57.928 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading services from folder: /home/pi/.bluetooth_smart/service
13:28:58.108 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading characteristics from folder: /home/pi/.bluetooth_smart/characteristic
```

Could you please also let me know where is your folder and how did you make it to be accessible by openhab user?

Here is where I have it:

```
pi@raspberrypi:~ $ pwd
/home/pi
pi@raspberrypi:~ $ ls -la
drwxr-xr-x  4 pi   pi      4096 Sep 11 13:25 .bluetooth_smart
```
And I have this in the binding config:

![image](https://user-images.githubusercontent.com/1161883/45332873-4117d380-b5c7-11e8-9cc4-33d89e98d959.png)

**Comment by vkolotov** [comment]
And the files:

```
pi@raspberrypi:~/.bluetooth_smart/characteristic $ pwd
/home/pi/.bluetooth_smart/characteristic
pi@raspberrypi:~/.bluetooth_smart/characteristic $ ls -la
-rw-r--r-- 1 pi pi  864 Jan 27  2017 org.vlad.characteristic.smart_lock_control_point.xml
-rw-r--r-- 1 pi pi  961 Feb 23  2018 org.vlad.characteristic.smart_lock_door_status.xml
-rw-r--r-- 1 pi pi  965 Feb 23  2018 org.vlad.characteristic.smart_lock_lock_status.xml
```

Effectively all users can read them, so OH user can so.

**Comment by CrispinP** [comment]
I was starting to wonder ;)

Ok, so here is the info - 
My file location
`/mnt/usb/openhab/conf/GATT`

I chmod' them to 777.
The GATT folder sits alongside the items and rules folders.

`[17:49:50] root@homeauto:~# ls -l /mnt/usb/openhab/conf/GATT/
total 8
drwxrwxrwx 2 openhab openhab 4096 Sep  8 06:43 characteristic
drwxrwxrwx 2 openhab openhab 4096 Sep  8 06:43 service
`
`18:06:00.575 [INFO ] [smarthome.event.ItemStateChangedEvent] - Kitchen_MotionSensor_Illumination changed from 95 to 100
18:06:00.663 [INFO ] [smarthome.event.ItemStateChangedEvent] - Kitchen_MotionSensor_LastMotion changed from 2018-09-11T18:05:00.086+0100 to 2018-09-11T18:06:00.592+0100
18:06:00.765 [INFO ] [smarthome.event.ItemStateChangedEvent] - Server_Radarr_Latency changed from 9.0 to 10.0
18:06:00.861 [INFO ] [smarthome.event.ItemStateChangedEvent] - Server_UBNT_Latency changed from 16.0 to 19.0
18:06:00.948 [INFO ] [home.event.GroupItemStateChangedEvent] - g_Servers_Latency changed from 16.0 to 19.0 through Server_UBNT_Latency
18:06:01.252 [ERROR] [e.smarthome.model.script.actions.HTTP] - Fatal transport error: java.util.concurrent.TimeoutException
18:06:01.355 [ERROR] [ome.model.script.Blinds - getPosition] - null
18:06:01.417 [INFO ] [ipt.Blinds - Front room - getPosition] - Unlocked
18:06:01.591 [WARN ] [home.model.script.Blinds - Front room] - getPosition - Waiting on other locks. Count:1
18:06:01.753 [INFO ] [ipt.Blinds - Front room - getPosition] - Locked
18:06:01.795 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel online is linked although the handler was already disposed.
18:06:01.781 [INFO ] [smarthome.event.InboxRemovedEvent    ] - Discovery Result with UID 'bluetooth:ble:F395303EDD4A' has been removed.
18:06:02.030 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel last-updated is linked although the handler was already disposed.
18:06:02.353 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel rssi is linked although the handler was already disposed.
18:06:02.569 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel tx-power is linked although the handler was already disposed.
18:06:02.686 [INFO ] [smarthome.event.ItemStateChangedEvent] - TumbleDryer_Power changed from 1.004611 to 1.080449
18:06:02.817 [ERROR] [e.smarthome.model.script.actions.HTTP] - Fatal transport error: java.util.concurrent.TimeoutException
18:06:02.795 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel estimated-distance is linked although the handler was already disposed.
18:06:02.948 [ERROR] [ome.model.script.Blinds - getPosition] - null
18:06:02.856 [INFO ] [home.event.GroupItemStateChangedEvent] - g_Appliances_Power_Sum changed from 84.004611 to 84.080449 through TumbleDryer_Power
18:06:03.253 [INFO ] [ipt.Blinds - Front room - getPosition] - Unlocked
18:06:03.196 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel adapter is linked although the handler was already disposed.
18:06:03.635 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel location is linked although the handler was already disposed.
18:06:03.811 [INFO ] [smarthome.event.ItemStateChangedEvent] - WashingMachine_Power changed from 0.0 to 0.287324
18:06:03.886 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel connected is linked although the handler was already disposed.
18:06:03.985 [INFO ] [home.event.GroupItemStateChangedEvent] - g_Appliances_Power_Sum changed from 84.080449 to 84.367773 through WashingMachine_Power
18:06:04.208 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel connection-control is linked although the handler was already disposed.
18:06:04.507 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel connected-adapter is linked although the handler was already disposed.
18:06:04.804 [WARN ] [e.core.thing.binding.BaseThingHandler] - Handler BluetoothDeviceHandler of thing bluetooth:ble:F395303EDD4A tried checking if channel authenticated is linked although the handler was already disposed.
18:06:05.035 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'bluetooth:ble:F395303EDD4A' changed from UNINITIALIZED to INITIALIZING
18:06:05.057 [WARN ] [e.core.thing.binding.BaseThingHandler] - BaseThingHandler.initialize() will be removed soon, ThingStatus can be set manually via updateStatus(ThingStatus.ONLINE)
18:06:05.102 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'bluetooth:ble:F395303EDD4A' has been updated.
18:06:05.282 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'bluetooth:ble:F395303EDD4A' changed from INITIALIZING to ONLINE
18:06:07.012 [INFO ] [ghtwaverf.internal.LightwaveRfBinding] - Update from LightwaveRf ItemName[Power_Solar_prxy], State[144]
18:06:07.749 [INFO ] [smarthome.event.ItemStateChangedEvent] - TumbleDryer_Power changed from 1.080449 to 4.454213
18:06:07.808 [INFO ] [home.event.GroupItemStateChangedEvent] - g_Appliances_Power_Sum changed from 84.367773 to 87.741537 through TumbleDryer_Power
18:06:08.863 [INFO ] [smarthome.event.ItemStateChangedEvent] - WashingMachine_Power changed from 0.287324 to 0.0
18:06:08.921 [INFO ] [home.event.GroupItemStateChangedEvent] - g_Appliances_Power_Sum changed from 87.741537 to 87.454213 through WashingMachine_Power
18:06:09.496 [INFO ] [ghtwaverf.internal.LightwaveRfBinding] - Update from LightwaveRf ItemName[Power_Main], State[800]
18:06:09.562 [INFO ] [smarthome.event.ItemStateChangedEvent] - Power_Main changed from 1071 to 800
18:06:09.781 [INFO ] [smarthome.event.ItemStateChangedEvent] - server_son_main_current changed from 0.524 to 0.515
`

I cannot see it log anything for the parser. 


I have the following installed - 
![image](https://user-images.githubusercontent.com/27884877/45375892-3ae91d80-b5ee-11e8-8f72-279b400ef050.png)

Confused....

**Comment by vkolotov** [comment]
Just checking. Have you specified `/mnt/usb/openhab/conf/GATT/` on the UI (binding settings)?

**Comment by CrispinP** [comment]
Yup. Exactly the same path

**Comment by vkolotov** [comment]
The log entries show up only when you save binding settings or when you restart OH. Could you please double check that you have enabled DEBUG level?

```
log:set DEBUG org.sputnikdev.bluetooth.gattparser.spec
```

**Comment by CrispinP** [comment]
Ok, I changed the location to be the same as yours (remove any doubt). I chmod 777 it as well. 
I then double-checked, changed and saved the binding settings. I see this in the log:

> 
06:56:15.274 [INFO ] [smarthome.event.InboxRemovedEvent    ] - Discovery Result with UID 'bluetooth:adapter:B827EB5EF917' has been removed.
06:56:15.293 [WARN ] [oth.manager.impl.BluetoothManagerImpl] - Disposing Bluetooth manager: 1301051
06:56:15.422 [WARN ] [.impl.AbstractBluetoothObjectGovernor] - Disposing governor: /B8:27:EB:5E:F9:17/F3:95:30:3E:DD:4A
06:56:15.526 [WARN ] [.impl.AbstractBluetoothObjectGovernor] - Disposing governor: /B8:27:EB:5E:F9:17/C1:03:74:91:05:6C
06:56:15.633 [WARN ] [.impl.AbstractBluetoothObjectGovernor] - Disposing governor: /B8:27:EB:5E:F9:17
06:56:15.748 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading services and characteristics from folder: /home/pi/.bluetooth_smart
06:56:15.897 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading services from folder: /home/pi/.bluetooth_smart/service
06:56:16.194 [INFO ] [spec.BluetoothGattSpecificationReader] - Reading characteristics from folder: /home/pi/.bluetooth_smart/characteristic


So it is reading the directory. Should it be listing the services and characteristics listed in there?
Are my files mal-formed?


Thanks for the help!

**Comment by vkolotov** [comment]
If there were malformed, then it would complain. So I believe they are loaded.

Can you please share your files here? Can you also please remove and add your device in OH? Do you enable "Connection Control"? When your devices gets connected, the binding discovers services and characteristics automatically. Also double check what you have here (binding settings):

![image](https://user-images.githubusercontent.com/1161883/45425511-b1207980-b6ed-11e8-9a2c-d2bf7265bd83.png)

**Comment by CrispinP** [comment]
I malformed one this morning and restarted it - it threw lots of nice errors about malformed xml. So, it's reading it.

My settings are the same as yours - 
![image](https://user-images.githubusercontent.com/27884877/45450023-c043ff00-b6ce-11e8-9690-2d64bdfbee61.png)


so....! I uninstalled the bindings and rebooted the Pi because it lost all the BT devices it could see. 
After that I set the control on and ta-DAAAAAAAA!

![image](https://user-images.githubusercontent.com/27884877/45451268-7eb55300-b6d2-11e8-91b6-8618b158081d.png)

Everything is now showing up - including the mapped ones of mine. :)

I'll now try get them working and talking proper. Once it's good I will send you the xml files for full inclusion.

Thanks for the help so far!

**Comment by CrispinP** [comment]
it's alive! :)

I see in the logs 

> 21:48:49.148 [INFO ] [smarthome.event.ItemStateChangedEvent] - Xxx_BlindPosition changed from 0.0 to 100.0
> 21:48:11.337 [INFO ] [smarthome.event.ItemStateChangedEvent] - utility_boiler_heating_flow changed from 28.50 to 29.00
> 21:48:11.359 [INFO ] [smarthome.event.ItemStateChangedEvent] - Xxx_BatteryLevel changed from 67.0 to 68.0
> 21:48:11.759 [INFO ] [smarthome.event.ItemStateChangedEvent] - Xxx_BatteryLevel changed from 68.0 to 67.0
> 21:48:14.243 [INFO ] [smarthome.event.ItemStateChangedEvent] - Xxx_BatteryLevel changed from 67.0 to 68.0
> 21:48:14.457 [INFO ] [smarthome.event.ItemStateChangedEvent] - Xxx_BatteryLevel changed from 68.0 to 67.0
> 21:48:15.337 [INFO ] [smarthome.event.ItemStateChangedEvent] - utility_boiler_heating_flow changed from 29.00 to 28.50

Now to build out the rest of the xml to suit everything :)

**Comment by vkolotov** [comment]
Nice one!

**Comment by CrispinP** [comment]
So I've created the target characteristic but it does not respond when I update the item to 69 or 96.
Other read only ones I created work just fine. 

Anything else I need to do to write?

**Comment by vkolotov** [comment]
Other than that you have to be connected - nope. Does it complain or something?
What transport do you use? TinyB or BlueGiga?

You may turn on DEBUG/TRACE levels for the transport:

```
log:info DEBUG org.sputnikdev.bluetooth.manager.transport.tinyb
log:info DEBUG org.sputnikdev.bluetooth.manager.transport.bluegiga
```

You should get something like that in the logs after enabling log levels and updating a characteristic:

```
10:45:21.223 [DEBUG] [r.transport.tinyb.TinyBCharacteristic] - Writing value: tinyb:/00:1A:7D:DA:71:04/CF:FC:9E:B2:0E:63/0000dd01-0000-1000-8000-00805f9b34fb/0000dda3-0000-1000-8000-00805f9b34fb
```

**Comment by vkolotov** [comment]
Most likely these numbers are actually in hex format:

MOTOR_MOVE_UP = 69
MOTOR_MOVE_DOWN = 96

so you will need to convert them

0x69 = 105
0x96 = 150

**Comment by CrispinP** [comment]
nope, no writing values 
 

> 06:55:56.283 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - Discovered adapters requested
> 06:55:56.296 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - Discovering adapters
> 06:55:56.319 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - Discovered ports: []
> 06:55:56.330 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - Ports already in use: []
> 06:55:56.340 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - New adapters: []
> 06:55:56.351 [DEBUG] [er.transport.bluegiga.BluegigaFactory] - Discovered adapters: []
> 06:55:56.441 [DEBUG] [r.transport.tinyb.TinyBCharacteristic] - Reading value: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C/00001861-b87f-490c-92cb-11ba5ea5167c/00001530-b87f-490c-92cb-11ba5ea5167c
> 06:55:58.542 [DEBUG] [r.transport.tinyb.TinyBCharacteristic] - Reading value: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C/00001861-b87f-490c-92cb-11ba5ea5167c/00001526-b87f-490c-92cb-11ba5ea5167c
> 06:55:58.986 [DEBUG] [h.manager.transport.tinyb.TinyBDevice] - Getting blocked: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C
> 06:55:59.000 [DEBUG] [h.manager.transport.tinyb.TinyBDevice] - Checking if device connected: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C
> 06:55:59.015 [DEBUG] [h.manager.transport.tinyb.TinyBDevice] - Getting RSSI: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C
> 06:55:59.032 [DEBUG] [h.manager.transport.tinyb.TinyBDevice] - Getting TxPower: tinyb://B8:27:EB:5E:F9:17/C1:03:74:91:05:6C
> 

Is the services file correct? Does it need to change to make it writable?

**Comment by CrispinP** [comment]
Scrap that, the position characteristic works. I send it an int (percentage) and the blind responds. So, it's just the motion stuff. Will work on it tonight.

**Comment by vkolotov** [comment]
Good stuff

**Comment by vkolotov** [comment]
check if it is hex vs decimal number

**Comment by CrispinP** [comment]
I did try but might have screwed up. Rushing for train to work... Will revert tonight

**Comment by CrispinP** [comment]
It's alive!
It is indeed hex. Thanks for the help. 

Last thing I am going to try is to get it mapped to UP/DOWN in the gatt file. Then I'll be done.

**Comment by vkolotov** [comment]
Good news, well done! Here is an example of how you can map some numeric values to options (displayed in OH as a dropdown box):

```
<?xml version="1.0" encoding="UTF-8"?><!-- Copyright 2011 Bluetooth SIG, Inc. All rights reserved. -->
<Characteristic xsi:noNamespaceSchemaLocation="http://schemas.bluetooth.org/Documents/characteristic.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                type="org.vlad.characteristic.smart_lock_control_point" name="Smart Lock Control Point"
                uuid="DDA3">
    <InformativeText></InformativeText>
    <Value>
        <Field name="Smart Lock Control Point">
            <Requirement>Mandatory</Requirement>
            <Format>8bit</Format>
            <Enumerations>
                <Enumeration key="1" value="Unlock"/>
                <Enumeration key="2" value="Lock"/>
                <ReservedForFutureUse start="3" end="255"/>
            </Enumerations>
        </Field>
    </Value>
</Characteristic>
```

Apart from naming it properly (name attribute),you will have something like that:

```
<Enumerations>
                <Enumeration key="105" value="Open"/>
                <Enumeration key="150" value="Close"/>
            </Enumerations>
```

**Comment by vkolotov** [comment]
It would be great if you could create a PR, I'll cut a new release after that.

Also, it would be superb useful if you could announce this on the OH forum thread (either on the official/existing or your own). 

Also, if you could make some screenshots, I would update some documentation for the binding.

Good work!

**Comment by CrispinP** [comment]
There is no doubt I will put posts up and do a PR for this. It's great having it bundled in now.

I'll close this issue too.
